services:
  rstudio:
    build:
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio
    environment:
      - DISABLE_AUTH=true
      - ROOT=true
    stdin_open: true  # docker run -i
    tty: true         # docker run -t