# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count the number of OpenMP threads for parallel computation
#'
#' \code{count_omp_thread()} counts the number of OpenMP threads for
#' parallel computation.
#' If it returns 1, OpenMP is not viable.
#'
#' @return
#' Number of OpenMP thread(s).
#'
#' @examples
#' count_omp_thread()
#'
#' @export
count_omp_thread <- function() {
    .Call(`_bartcs_count_omp_thread`)
}

fit_separate <- function(Y1, Y0, var_count, var_prob, sigma2_out1_hist, sigma2_out0_hist, dir_alpha_hist, Y_treated, Y_control, trt, X, X_treated, X_control, chain_idx, num_chain, total_iter, num_burn_in, num_thin, num_post_sample, num_tree, step_prob, alpha, beta, nu, lambda_out1, lambda_out0, is_binary_trt, parallel, verbose) {
    invisible(.Call(`_bartcs_fit_separate`, Y1, Y0, var_count, var_prob, sigma2_out1_hist, sigma2_out0_hist, dir_alpha_hist, Y_treated, Y_control, trt, X, X_treated, X_control, chain_idx, num_chain, total_iter, num_burn_in, num_thin, num_post_sample, num_tree, step_prob, alpha, beta, nu, lambda_out1, lambda_out0, is_binary_trt, parallel, verbose))
}

fit_single <- function(Y1, Y0, var_count, var_prob, sigma2_exp, sigma2_out_hist, dir_alpha_hist, Y, trt, X, trt_treated, trt_control, chain_idx, num_chain, total_iter, num_burn_in, num_thin, num_post_sample, num_tree, step_prob, alpha, beta, nu, lambda_exp, lambda_out, is_binary_trt, parallel, verbose) {
    invisible(.Call(`_bartcs_fit_single`, Y1, Y0, var_count, var_prob, sigma2_exp, sigma2_out_hist, dir_alpha_hist, Y, trt, X, trt_treated, trt_control, chain_idx, num_chain, total_iter, num_burn_in, num_thin, num_post_sample, num_tree, step_prob, alpha, beta, nu, lambda_exp, lambda_out, is_binary_trt, parallel, verbose))
}

