# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count the number of OpenMP threads for parallel computation
#'
#' \code{count_omp_thread()} counts the number of OpenMP threads for
#' parallel computation.
#' If it returns 1, OpenMP is not viable.
#'
#' @return
#' Number of OpenMP thread(s).
#'
#' @examples
#' count_omp_thread()
#'
#' @export
count_omp_thread <- function() {
    .Call(`_bartcs_count_omp_thread`)
}

cseparate_bart <- function(X_src, Y1_src, X1_src, Y0_src, X0_src, TRT_src, Y_min, Y_max, step_prob, num_chain, num_chain_iter, num_burn_in, num_thin, num_post_sample, num_tree, alpha, beta, nu, lambda_out1, lambda_out0, initial_dir_alpha, initial_sigma2_out1, initial_sigma2_out0, parallel, verbose) {
    .Call(`_bartcs_cseparate_bart`, X_src, Y1_src, X1_src, Y0_src, X0_src, TRT_src, Y_min, Y_max, step_prob, num_chain, num_chain_iter, num_burn_in, num_thin, num_post_sample, num_tree, alpha, beta, nu, lambda_out1, lambda_out0, initial_dir_alpha, initial_sigma2_out1, initial_sigma2_out0, parallel, verbose)
}

csingle_bart <- function(Y_src, X_src, TRT_src, trt_treated, trt_control, Y_min, Y_max, step_prob, num_chain, num_chain_iter, num_burn_in, num_thin, num_post_sample, num_tree, alpha, beta, nu, lambda_exp, lambda_out, initial_dir_alpha, initial_sigma2_exp, initial_sigma2_out, binary_trt, parallel, verbose) {
    .Call(`_bartcs_csingle_bart`, Y_src, X_src, TRT_src, trt_treated, trt_control, Y_min, Y_max, step_prob, num_chain, num_chain_iter, num_burn_in, num_thin, num_post_sample, num_tree, alpha, beta, nu, lambda_exp, lambda_out, initial_dir_alpha, initial_sigma2_exp, initial_sigma2_out, binary_trt, parallel, verbose)
}

